/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.akillisehirsistemi.views;

import com.mycompany.akillisehirsistemi.models.user.Admin;
import javax.swing.JOptionPane;

/**
 *
 * @author EMD
 */
public class AdminGiris extends javax.swing.JFrame {

    /**
     * Creates new form AdminGiris
     */
    public AdminGiris() {
        initComponents();
        this.setLayout(null); // Layout'u devre dışı bırak

        // JLabel'in içeriğini ortala
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        // JLabel'in kendisini ortala
        int frameWidth = this.getWidth();
        int labelWidth = jLabel1.getPreferredSize().width;
        int newX = (frameWidth - labelWidth) / 2;
        jLabel1.setBounds(newX, jLabel1.getY(), labelWidth, jLabel1.getHeight());

        int labelWidth2 = jLabel2.getPreferredSize().width;
        int newX2 = (frameWidth - labelWidth2) / 2;
        jLabel2.setBounds(newX2, jLabel2.getY(), labelWidth2, jLabel2.getHeight());

        int labelWidth3 = jLabel3.getPreferredSize().width;
        int newX3 = (frameWidth - labelWidth3) / 2;
        jLabel3.setBounds(newX3, jLabel3.getY(), labelWidth3, jLabel3.getHeight());

        // Butonu yatay olarak ortala
        int buttonWidth = btn.getPreferredSize().width;
        int buttonX = (frameWidth - buttonWidth) / 2; // Yatay ortalama
        btn.setBounds(buttonX, btn.getY(), buttonWidth, btn.getHeight());

        // Butonu yatay olarak ortala
        int buttonWidth1 = btn1.getPreferredSize().width;
        int buttonX1 = (frameWidth - buttonWidth1) / 2; // Yatay ortalama
        btn1.setBounds(buttonX1, btn1.getY(), buttonWidth1, btn1.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        adminAd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        adminNo = new javax.swing.JTextField();
        btn = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Admin Giris Sayfasi");

        jLabel2.setText("Adinizi Giriniz");

        adminAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminIsimTextFiled(evt);
            }
        });

        jLabel3.setText("Numaranizi Giriniz");

        adminNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminNoTextFiled(evt);
            }
        });

        btn.setText("Giris ");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminGirisButon(evt);
            }
        });

        btn1.setText("Kapat");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminGirisKapatBotun(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn1))
                .addGap(155, 155, 155))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 237, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(244, 244, 244))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(adminAd, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminNo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(211, 211, 211))))
            .addGroup(layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(adminAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(adminNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btn)
                .addGap(18, 18, 18)
                .addComponent(btn1)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminIsimTextFiled(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminIsimTextFiled
        // TODO add your handling code here:
    }//GEN-LAST:event_adminIsimTextFiled

    private void adminNoTextFiled(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminNoTextFiled
        // TODO add your handling code here:
    }//GEN-LAST:event_adminNoTextFiled

    private void adminGirisButon(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminGirisButon

        if (adminAd.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lutfen Adinizi Giriniz", "Bos Alan", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (adminNo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lutfen Admin Numaranizi Giriniz", "Bos Alan", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int no;
        try {
            no = Integer.parseInt(adminNo.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Admin Numaraniz sadece sayilardan olusmalidir!", "Geçersiz Giriş", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String name = adminAd.getText();
        
        Admin admin = Admin.getInstance();
        AdminDashBoard adminDashBoard = new AdminDashBoard();
        boolean bol = admin.giris_Yap(name, no);
        
        if (bol) {
            adminDashBoard.setLocationRelativeTo(null);
            adminDashBoard.setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Yanlis Bilgi Girisi!!\nBilgilerinizden Emin Olup Bir Daha Deneyiniz");
        }
    }//GEN-LAST:event_adminGirisButon

    private void adminGirisKapatBotun(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminGirisKapatBotun
        // TODO add your handling code here:
        setVisible(false);
        Home home = new Home();
        home.setLocationRelativeTo(null);
        home.setVisible(true);
    }//GEN-LAST:event_adminGirisKapatBotun

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminGiris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminAd;
    private javax.swing.JTextField adminNo;
    private javax.swing.JButton btn;
    private javax.swing.JButton btn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
