/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.akillisehirsistemi.views;

/**
 *
 * @author EMD
 */
public class AdminDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashBoard
     */
    public AdminDashBoard() {
        initComponents();
        this.setLayout(null); // Layout'u devre dışı bırak

        // JLabel'in içeriğini ortala
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        // JLabel'in kendisini ortala
        int frameWidth = this.getWidth();
        int labelWidth = jLabel1.getPreferredSize().width;
        int newX = (frameWidth - labelWidth) / 2;
        jLabel1.setBounds(newX, jLabel1.getY(), labelWidth, jLabel1.getHeight());

        // Butonu yatay olarak ortala
        int buttonWidth = btn.getPreferredSize().width;
        int buttonX = (frameWidth - buttonWidth) / 2; // Yatay ortalama
        btn.setBounds(buttonX, btn.getY(), buttonWidth, btn.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Admin Yonetim Sayfasi");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Varlik Ekleme Islemleri");

        jButton2.setText("Devam");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eklemeSayfasiButon(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Varlik Guncelleme Islemleri");

        jButton1.setText("Devam");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varlikGuncellemeButon(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Hizmet Durumlarini Izle");

        jButton3.setText("Devam");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hizmetIzlemeButon(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("HIzmet Raporu Uret");

        jButton4.setText("Devam");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raporUretButon(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Sistem Uyarilari");

        jButton5.setText("Devam");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uyariSayfisiButon(evt);
            }
        });

        btn.setText("Geri");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminGirisSafasiDon(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(btn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btn)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eklemeSayfasiButon(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eklemeSayfasiButon
        // TODO add your handling code here:
        VarlikEkleme varlikEkleme = new VarlikEkleme();
        varlikEkleme.setLocationRelativeTo(null);
        varlikEkleme.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_eklemeSayfasiButon

    private void varlikGuncellemeButon(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varlikGuncellemeButon
        // TODO add your handling code here:
        VarlikGuncelleme varlikGuncelleme = new VarlikGuncelleme();
        varlikGuncelleme.setLocationRelativeTo(null);
        varlikGuncelleme.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_varlikGuncellemeButon

    private void hizmetIzlemeButon(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hizmetIzlemeButon
        // TODO add your handling code here:
        HizmetDurumlariniIzleme hizmetDurumlariniIzleme = new HizmetDurumlariniIzleme();
        hizmetDurumlariniIzleme.setLocationRelativeTo(null);
        hizmetDurumlariniIzleme.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_hizmetIzlemeButon

    private void raporUretButon(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raporUretButon
        // TODO add your handling code here:
        HizmetRaporuUretme hizmetRaporuUretme = new HizmetRaporuUretme();
        hizmetRaporuUretme.setLocationRelativeTo(null);
        hizmetRaporuUretme.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_raporUretButon

    private void uyariSayfisiButon(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uyariSayfisiButon
        // TODO add your handling code here:
        SistemUyarilari sistemUyarilari = new SistemUyarilari();
        sistemUyarilari.setLocationRelativeTo(null);
        sistemUyarilari.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_uyariSayfisiButon

    private void adminGirisSafasiDon(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminGirisSafasiDon
        // TODO add your handling code here:
        AdminGiris adminGiris = new AdminGiris();
        adminGiris.setLocationRelativeTo(null);
        adminGiris.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_adminGirisSafasiDon

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
