/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.akillisehirsistemi.views;

import com.mycompany.akillisehirsistemi.models.enerjySource.EnergySource;
import com.mycompany.akillisehirsistemi.controllers.EnergyManagement;
import javax.swing.JOptionPane;

/**
 *
 * @author EMD
 */
public class EnerjiKaynagiGuncelleme extends javax.swing.JFrame {

    EnergyManagement energyManagement = EnergyManagement.getInstance();
    private EnergySource energySource;

    /**
     * Creates new form EnerjiKaynagiGuncelleme
     */
    public EnerjiKaynagiGuncelleme() {
        initComponents();

        uretimList.setEnabled(false);
        kapasiteList.setEnabled(false);

        this.setLayout(null); // Layout'u devre dışı bırak

        // JLabel'in içeriğini ortala
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        // JLabel'in kendisini ortala
        int frameWidth = this.getWidth();
        int labelWidth = jLabel1.getPreferredSize().width;
        int newX = (frameWidth - labelWidth) / 2;
        jLabel1.setBounds(newX, jLabel1.getY(), labelWidth, jLabel1.getHeight());

        // Butonu yatay olarak ortala
        int buttonWidth = jButton1.getPreferredSize().width;
        int buttonX = (frameWidth - buttonWidth) / 2; // Yatay ortalama
        jButton1.setBounds(buttonX, jButton1.getY(), buttonWidth, jButton1.getHeight());

        int buttonWidth2 = btnKaydet.getPreferredSize().width;
        int buttonX2 = (frameWidth - buttonWidth2) / 2; // Yatay ortalama
        btnKaydet.setBounds(buttonX2, btnKaydet.getY(), buttonWidth2, btnKaydet.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        numaraText = new javax.swing.JTextPane();
        devamButon = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        uretimList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        kapasiteList = new javax.swing.JList<>();
        btnKaydet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Geri");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Enerji Kaynaklari Guncelleme Sayfasi");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Kaynak Numarasini Giriniz ve Devam Tusuna Basiniz :");

        jScrollPane1.setViewportView(numaraText);

        devamButon.setText("Devam");
        devamButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devamButon(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Altta Cikacak Olan Bilgileri Degistirerek Kaydet Tusuna Basarak Guncellemis Olursunuz :");

        jLabel4.setText("Gunluk Uretim :");

        jLabel5.setText("Kapasite :");

        uretimList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "3000 LT", "7000 LT", "---------", "3000 kW", "7000 kW" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(uretimList);

        kapasiteList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "10000 LT", "----------", "10000 kW" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(kapasiteList);

        btnKaydet.setText("Kaydet");
        btnKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetButon(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(devamButon)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(21, 21, 21))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(384, 384, 384)))
                        .addGap(0, 44, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKaydet)
                        .addGap(60, 60, 60)))
                .addGap(220, 220, 220))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(devamButon)
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnKaydet)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        VarlikGuncelleme varlikGuncelleme = new VarlikGuncelleme();
        varlikGuncelleme.setLocationRelativeTo(null);
        varlikGuncelleme.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void devamButon(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devamButon
        String uretim = uretimList.getSelectedValue();
        String kapasite = kapasiteList.getSelectedValue();
        String kaynakNumarasi = numaraText.getText();
        try {
            for (EnergySource source : EnergyManagement.getInstance().kaynaklarListesi) {
                if (kaynakNumarasi.equals(source.getKaynakNumarasi())) {
                    energySource = source;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hata: " + e.getMessage(), "Yanlis Bilgi Girisi", JOptionPane.ERROR_MESSAGE);
        }
        uretimList.setEnabled(true);
        kapasiteList.setEnabled(true);
        
        if (energySource.getTip().equals("Fosil Yakit Kaynagi")) {
            //Fosil yakıt ve su kaynaklarının seçeneklerini aktif kılar 
            uretimList.setSelectionInterval(0, 1); // Sadece 0 ve 1 seçilebilir
            kapasiteList.setSelectionInterval(0, 0); // Sadece 0 seçilebilir
            //uretimList.getSelectedIndex().setEnabled(false);
        } else {
            //Diğer kaynaklarının seçeneklerini aktif kılar 
            uretimList.setSelectionInterval(3, 4); // Sadece 3 ve 4 seçilebilir
            kapasiteList.setSelectionInterval(2, 2); // Sadece 2 seçilebilir
        }
    }//GEN-LAST:event_devamButon

    private void kaydetButon(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetButon

        String uretim = uretimList.getSelectedValue();
        String kapasite = kapasiteList.getSelectedValue();

        String uretimNumarasi = uretim.split(" ")[0];
        String kapasiteNumarasi = kapasite.split(" ")[0];

        int ur = Integer.parseInt(uretimNumarasi);
        int kap = Integer.parseInt(kapasiteNumarasi);

        this.energySource.setGunlukUretim(ur);
        this.energySource.setKapasite(kap);

        JOptionPane.showMessageDialog(null, "Bilgiler Basariyla guncellendi", "Bilgi Guncelleme", JOptionPane.INFORMATION_MESSAGE);
        VarlikGuncelleme varlikGuncelleme = new VarlikGuncelleme();
        varlikGuncelleme.setLocationRelativeTo(null);
        varlikGuncelleme.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_kaydetButon

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnerjiKaynagiGuncelleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnerjiKaynagiGuncelleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnerjiKaynagiGuncelleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnerjiKaynagiGuncelleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnerjiKaynagiGuncelleme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKaydet;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton devamButon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> kapasiteList;
    private javax.swing.JTextPane numaraText;
    private javax.swing.JList<String> uretimList;
    // End of variables declaration//GEN-END:variables
}
