/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.akillisehirsistemi.views;

import com.mycompany.akillisehirsistemi.controllers.EnergyManagement;
import com.mycompany.akillisehirsistemi.models.user.Admin;
import com.mycompany.akillisehirsistemi.models.enerjySource.EnergySource;
import javax.swing.JOptionPane;

/**
 *
 * @author EMD
 */
public class EnerjiKaynagiEkelme extends javax.swing.JFrame {
    boolean bol;
    public EnerjiKaynagiEkelme(boolean bol) {
        initComponents();
        this.setLayout(null); // Layout'u devre dışı bırak

        // JLabel'in içeriğini ortala
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        // JLabel'in kendisini ortala
        int frameWidth = this.getWidth();
        int labelWidth = jLabel1.getPreferredSize().width;
        int newX = (frameWidth - labelWidth) / 2;
        jLabel1.setBounds(newX, jLabel1.getY(), labelWidth, jLabel1.getHeight());

        // Butonu yatay olarak ortala
        int buttonWidth = jButton2.getPreferredSize().width;
        int buttonX = (frameWidth - buttonWidth) / 2; // Yatay ortalama
        jButton2.setBounds(buttonX, jButton2.getY(), buttonWidth, jButton2.getHeight());

        // Butonu yatay olarak ortala
        int buttonWidth1 = jButton1.getPreferredSize().width;
        int buttonX1 = (frameWidth - buttonWidth1) / 2; // Yatay ortalama
        jButton1.setBounds(buttonX1, jButton1.getY(), buttonWidth1, jButton1.getHeight());
        this.bol = bol;
    }

    public EnerjiKaynagiEkelme() {
        initComponents();
        this.setLayout(null); // Layout'u devre dışı bırak

        // JLabel'in içeriğini ortala
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        // JLabel'in kendisini ortala
        int frameWidth = this.getWidth();
        int labelWidth = jLabel1.getPreferredSize().width;
        int newX = (frameWidth - labelWidth) / 2;
        jLabel1.setBounds(newX, jLabel1.getY(), labelWidth, jLabel1.getHeight());

        // Butonu yatay olarak ortala
        int buttonWidth = jButton2.getPreferredSize().width;
        int buttonX = (frameWidth - buttonWidth) / 2; // Yatay ortalama
        jButton2.setBounds(buttonX, jButton2.getY(), buttonWidth, jButton2.getHeight());

        // Butonu yatay olarak ortala
        int buttonWidth1 = jButton1.getPreferredSize().width;
        int buttonX1 = (frameWidth - buttonWidth1) / 2; // Yatay ortalama
        jButton1.setBounds(buttonX1, jButton1.getY(), buttonWidth1, jButton1.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tipList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        kapasiteList = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        uretimList = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        numaraText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Geri");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varlikEklemeSayfsinaDonus(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Enerji Kaynagi Ekleme Islemleri");

        tipList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tipList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fosil Yakit Kaynagi", " ", "Gunes Kaynagi", " ", "Nukleer Kaynagi ", " ", "Ruzgar Kaynagi", " ", "Su Kaynagi" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        tipList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tipList);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Bina Tipi Seciniz :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Kaynagin Kapasitesini Giriniz");

        kapasiteList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kapasiteList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "10000 LT", "10000 kW" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        kapasiteList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(kapasiteList);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Kaynagin Gunluk Uretimini Belirleyizin");

        uretimList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        uretimList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "2000 LT", "5000 LT", "---------", "2000 kW", "5000 kW" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        uretimList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(uretimList);

        jButton2.setText("Ekle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enerjyKaynagiEkle(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Kaynak Numarasini Giriniz :");

        jLabel6.setText("(Kaynak Numarsi Alttaki Formatta Olmasi Gerek)");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("\"kaynakTipi-numarasi\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 115, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(35, 35, 35)
                                            .addComponent(numaraText, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(126, 126, 126))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(255, 255, 255))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(149, 149, 149))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(numaraText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void varlikEklemeSayfsinaDonus(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varlikEklemeSayfsinaDonus
        // TODO add your handling code here:
        if(bol) {
            JOptionPane.showMessageDialog(null, "Sorun çözme sayfasından geldiğiniz için enerji kaynağı eklemeden çıkamazsınız", "Bilgilendirme Mesajı", JOptionPane.INFORMATION_MESSAGE);
            return;
        }else{
            VarlikEkleme varlikEkleme = new VarlikEkleme();
            varlikEkleme.setLocationRelativeTo(null);
            varlikEkleme.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_varlikEklemeSayfsinaDonus

    private void enerjyKaynagiEkle(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enerjyKaynagiEkle
        Admin admin = Admin.getInstance();
        String tip = tipList.getSelectedValue();
        String kapasiteString = kapasiteList.getSelectedValue();
        String gunlukUretimString = uretimList.getSelectedValue();
        String numara = numaraText.getText();
// Listelerdeki seçim kontrolü
        if (tip == null || kapasiteString == null || gunlukUretimString == null) {
            JOptionPane.showMessageDialog(null, "Lütfen tüm listelerden bir seçim yapın!", "Eksik Bilgi", JOptionPane.WARNING_MESSAGE);
            return; // Metodu sonlandır
        }
        if (this.tipList.getSelectedIndex() == 1 || tipList.getSelectedIndex() == 3 || tipList.getSelectedIndex() == 5 || tipList.getSelectedIndex() == 7) {
            JOptionPane.showMessageDialog(null, "Lütfen Geçerli Bir Enerji Kaynağı Tipi Seçiniz!", "Boş Seçim", JOptionPane.WARNING_MESSAGE);
            return; // Metodu sonlandır
        }

// Numara kontrolü
        if (numara.isEmpty()) {  // Boşluk kontrolü
            JOptionPane.showMessageDialog(null, "Lütfen bir numara girin!", "Eksik Bilgi", JOptionPane.WARNING_MESSAGE);
            return; // Metodu sonlandır
        }
        if (!numara.matches("[a-zA-ZçÇğĞıİöÖşŞüÜ]+-\\d+")) {  // Format: kaynakTipi-numarası
            JOptionPane.showMessageDialog(null, "Numara geçerli bir formatta olmalıdır! Örnek: Gunes-1234", "Geçersiz Giriş", JOptionPane.WARNING_MESSAGE);
            return; // Metodu sonlandır
        }
        try {
            boolean check = false;
            for (EnergySource energySource : EnergyManagement.getInstance().kaynaklarListesi) {
                if (energySource.getKaynakNumarasi().equals(numara)) {
                    check = true;
                    break;
                }
            }
            // Harf içeren String'lerin sayısal kısmını int değeri olarak saklama
            String kapasiteNumarasi = kapasiteString.split(" ")[0];
            int kapasite = Integer.parseInt(kapasiteNumarasi);
            String gunlukUretimNumarasi = gunlukUretimString.split(" ")[0];
            int gunlukUretim = Integer.parseInt(gunlukUretimNumarasi);

            if (check) {
                JOptionPane.showMessageDialog(null, "Lütfen Kullanılmayan Bir enerji kaynağı numarası girin!", "Mevcut Plaka Kullanım Hatası", JOptionPane.WARNING_MESSAGE);
                return;
            } else {
                // Admin işlemi
                admin.enerjiKaynagiEkleme(gunlukUretim, tip, kapasite, numara);
                // Başarı mesajı
                JOptionPane.showMessageDialog(null, tip + " başarıyla eklendi!", "Başarılı", JOptionPane.INFORMATION_MESSAGE);
                //Sistem uyarilari sayfasindan gelinmisse if calisir, varlik sayfasindan gelinmisse else calisir
                if (bol) {
                    bol = false;
                    SistemUyarilari sistemUyarilari = new SistemUyarilari();
                    sistemUyarilari.setLocationRelativeTo(null);
                    sistemUyarilari.setVisible(true);
                    setVisible(false);
                } else {
                    VarlikEkleme varlikEkleme = new VarlikEkleme();
                    varlikEkleme.setLocationRelativeTo(null);
                    varlikEkleme.setVisible(true);
                    setVisible(false);
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Kapasite veya Günlük Üretim sayısal bir değer içermelidir!", "Geçersiz Veri", JOptionPane.ERROR_MESSAGE);
            return;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hata: " + e.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_enerjyKaynagiEkle

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnerjiKaynagiEkelme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnerjiKaynagiEkelme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnerjiKaynagiEkelme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnerjiKaynagiEkelme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnerjiKaynagiEkelme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> kapasiteList;
    private javax.swing.JTextField numaraText;
    private javax.swing.JList<String> tipList;
    private javax.swing.JList<String> uretimList;
    // End of variables declaration//GEN-END:variables
}
