/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.akillisehirsistemi.views;

import javax.swing.table.DefaultTableModel;
import com.mycompany.akillisehirsistemi.models.user.Admin;
import javax.swing.JOptionPane;

/**
 *
 * @author EMD
 */
public class SistemUyarilari extends javax.swing.JFrame {

    /**
     * Creates new form SistemUyarilari
     */
    public SistemUyarilari() {
        initComponents();
        this.setLayout(null); // Layout'u devre dışı bırak

        // JLabel'in içeriğini ortala
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        // JLabel'in kendisini ortala
        int frameWidth = this.getWidth();
        int labelWidth = jLabel1.getPreferredSize().width;
        int newX = (frameWidth - labelWidth) / 2;
        jLabel1.setBounds(newX, jLabel1.getY(), labelWidth, jLabel1.getHeight());

        // Butonu yatay olarak ortala
        int buttonWidth = btn.getPreferredSize().width;
        int buttonX = (frameWidth - buttonWidth) / 2; // Yatay ortalama
        btn.setBounds(buttonX, btn.getY(), buttonWidth, btn.getHeight());

        int buttonWidth2 = btn2.getPreferredSize().width;
        int buttonX2 = (frameWidth - buttonWidth2) / 2; // Yatay ortalama
        btn2.setBounds(buttonX2, btn2.getY(), buttonWidth2, btn2.getHeight());

        //Tablo Olusturma ve Doldurma Islemleri
        DefaultTableModel tableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                // Hiçbir hücrenin düzenlenebilir olmamasını sağlıyoruz
                return false;
            }
        };

        tableModel.addColumn("Sistem Uyarilari");
        for (String str : Admin.getInstance().uyarilarListesi) {
            tableModel.addRow(new Object[]{str});
        }
        uyariTable.setModel(tableModel);

        // Hücre seçimini etkinleştir
        uyariTable.setCellSelectionEnabled(true);

        // Sadece tek bir hücre seçilsin
        uyariTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        uyariTable = new javax.swing.JTable();
        btn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn.setText("Geri");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminYonetimSayfasinaDonus(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Sistem Uyarilari Sayfasi");

        uyariTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(uyariTable);

        btn2.setText("Sorunu Coz");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn2)
                            .addComponent(btn))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btn2)
                .addGap(18, 18, 18)
                .addComponent(btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminYonetimSayfasinaDonus(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminYonetimSayfasinaDonus
        // TODO add your handling code here:
        AdminDashBoard adminDashBoard = new AdminDashBoard();
        adminDashBoard.setLocationRelativeTo(null);
        adminDashBoard.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_adminYonetimSayfasinaDonus

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        //int selectedRow = uyariTable.getSelectedRow(); // Seçilen satırı al

        if (uyariTable.getSelectedRow() != -1) { // Satır seçilmişse
            DefaultTableModel model = (DefaultTableModel) uyariTable.getModel(); // Modeli al

            // Seçilen satırın ilk sütunundaki veriyi alın (veya hangi sütundaysa)
            String secilenUyari = (String) model.getValueAt(uyariTable.getSelectedRow(), 0);
            if (secilenUyari.equals("A bolgesinde kalabalik var") || secilenUyari.equals("B bolgesinde kalabalik var") || secilenUyari.equals("C bolgesinde kalabalik var") || secilenUyari.equals("D bolgesinde kalabalik var")) {
                // Tablo satırını sil
                model.removeRow(uyariTable.getSelectedRow());

                // Listeyi güncelle
                Admin.getInstance().uyarilarListesi.removeIf(str -> str.equals(secilenUyari));
                JOptionPane.showMessageDialog(null, "Trafik Sıkışıklığı Sorunu Çözüldü ..", "Bilgilendirme", JOptionPane.INFORMATION_MESSAGE);
            } else {
                try {
                    JOptionPane.showMessageDialog(null, "Enerji Kaynaklari Ekleme Sayfasina Yonlendiriliyor..", "Bilgilendirme", JOptionPane.INFORMATION_MESSAGE);

                    // Tablo satırını sil
                    model.removeRow(uyariTable.getSelectedRow());

                    // Listeyi güncelle
                    Admin.getInstance().uyarilarListesi.removeIf(str -> str.equals(secilenUyari));

                    boolean bol = true;
                    EnerjiKaynagiEkelme enerjiKaynagiEkelme = new EnerjiKaynagiEkelme(bol);
                    enerjiKaynagiEkelme.setLocationRelativeTo(null);
                    enerjiKaynagiEkelme.setVisible(true);
                    setVisible(false);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Sorun Çözülemedi", "Hata Mesajı", JOptionPane.WARNING_MESSAGE);
                }
            }
        } else { // Hiçbir satır seçilmemişse
            JOptionPane.showMessageDialog(null, "Lütfen bir satır seçin!", "Boş Seçim", JOptionPane.WARNING_MESSAGE);
        }
//        if (secim.equals("Su tuketimi, rezerv seviyelerini asmistir") || secim.equals("Su rezerv miktari dusuktur")){
//            EnerjiKaynagiEkelme enerjiKaynagiEkelme = new EnerjiKaynagiEkelme();
//            enerjiKaynagiEkelme.setLocationRelativeTo(null);
//            enerjiKaynagiEkelme.setVisible(true);
//            setVisible(false);
//        }
//        if (secim.equals("Elektrik Tuketimi, Uretimi Asmistir") || secim.equals("Yakit Tuketimi, Uretimi Asmistir")) {
//            
//        }
    }//GEN-LAST:event_btn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemUyarilari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemUyarilari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemUyarilari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemUyarilari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemUyarilari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton btn2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable uyariTable;
    // End of variables declaration//GEN-END:variables
}
