/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.akillisehirsistemi.views;

/**
 *
 * @author EMD
 */
public class VarlikEkleme extends javax.swing.JFrame {

    /**
     * Creates new form VarlikEkleme
     */
    public VarlikEkleme() {
        initComponents();
        this.setLayout(null); // Layout'u devre dışı bırak

        // JLabel'in içeriğini ortala
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        // JLabel'in kendisini ortala
        int frameWidth = this.getWidth();
        int labelWidth = jLabel1.getPreferredSize().width;
        int newX = (frameWidth - labelWidth) / 2;
        jLabel1.setBounds(newX, jLabel1.getY(), labelWidth, jLabel1.getHeight());
        
        // Butonu yatay olarak ortala
        int buttonWidth = btn.getPreferredSize().width;
        int buttonX = (frameWidth - buttonWidth) / 2; // Yatay ortalama
        btn.setBounds(buttonX, btn.getY(), buttonWidth, btn.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn.setText("Geri");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminYonetimSayfasinaDonus(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Varlik Ekelme Sayfasi");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Araba Eklemek Icin Tiklayiniz");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Bina Eklemek Icin Tiklayiniz");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Enerji Kaynagi Eklemek Icin Tiklayiniz");

        jButton1.setText("Devam");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arabaEklelmeSayfasi(evt);
            }
        });

        jButton2.setText("Devam");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bineEklemeSayfasi(evt);
            }
        });

        jButton3.setText("Devam");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enerjiKaynagiEklemeSayfasi(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(btn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jLabel1)))
                        .addGap(0, 276, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 284, Short.MAX_VALUE)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton2))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(btn)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminYonetimSayfasinaDonus(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminYonetimSayfasinaDonus
        // TODO add your handling code here:
        setVisible(false);
        AdminDashBoard adminDashBoard = new AdminDashBoard();
        adminDashBoard.setLocationRelativeTo(null);
        adminDashBoard.setVisible(true);
    }//GEN-LAST:event_adminYonetimSayfasinaDonus

    private void arabaEklelmeSayfasi(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arabaEklelmeSayfasi
        // TODO add your handling code here:
        ArabaEkleme arabaEkleme = new ArabaEkleme();
        arabaEkleme.setLocationRelativeTo(null);
        arabaEkleme.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_arabaEklelmeSayfasi

    private void bineEklemeSayfasi(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bineEklemeSayfasi
        // TODO add your handling code here:
        BinaEkleme binaEkleme = new BinaEkleme();
        binaEkleme.setLocationRelativeTo(null);
        binaEkleme.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_bineEklemeSayfasi

    private void enerjiKaynagiEklemeSayfasi(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enerjiKaynagiEklemeSayfasi
        // TODO add your handling code here:
        EnerjiKaynagiEkelme enerjiKaynagiEkelme = new EnerjiKaynagiEkelme();
        enerjiKaynagiEkelme.setLocationRelativeTo(null);
        enerjiKaynagiEkelme.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_enerjiKaynagiEklemeSayfasi

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VarlikEkleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VarlikEkleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VarlikEkleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VarlikEkleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VarlikEkleme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
