/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.akillisehirsistemi.views;

import com.mycompany.akillisehirsistemi.models.user.Citizen;
import javax.swing.JOptionPane;
/**
 *
 * @author EMD
 */
public class VatandasGiris extends javax.swing.JFrame {

    /**
     * Creates new form VatandasGiris
     */
    public VatandasGiris() {
        initComponents();
        this.setLayout(null); // Layout'u devre dışı bırak

        // JLabel'in içeriğini ortala
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        // JLabel'in kendisini ortala
        int frameWidth = this.getWidth();
        int labelWidth = jLabel1.getPreferredSize().width;
        int newX = (frameWidth - labelWidth) / 2;
        jLabel1.setBounds(newX, jLabel1.getY(), labelWidth, jLabel1.getHeight());
        
        int labelWidth2 = jLabel2.getPreferredSize().width;
        int newX2 = (frameWidth - labelWidth2) / 2;
        jLabel2.setBounds(newX2, jLabel2.getY(), labelWidth2, jLabel2.getHeight());
        
        int labelWidth3 = jLabel3.getPreferredSize().width;
        int newX3 = (frameWidth - labelWidth3) / 2;
        jLabel3.setBounds(newX3, jLabel3.getY(), labelWidth3, jLabel3.getHeight());
        
        // Butonu yatay olarak ortala
        int buttonWidth = btn.getPreferredSize().width;
        int buttonX = (frameWidth - buttonWidth) / 2; // Yatay ortalama
        btn.setBounds(buttonX, btn.getY(), buttonWidth, btn.getHeight());
        
        // Butonu yatay olarak ortala
        int buttonWidth1 = btn1.getPreferredSize().width;
        int buttonX1 = (frameWidth - buttonWidth1) / 2; // Yatay ortalama
        btn1.setBounds(buttonX1, btn1.getY(), buttonWidth1, btn1.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        vatandasName = new javax.swing.JTextField();
        vatandasSifre = new javax.swing.JTextField();
        btn = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Vatandas Giris Sayfasi");
        jLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                metot1(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel2.setText("Adinizi Giriniz");

        jLabel3.setText("Sifrenizi Giriniz");

        vatandasName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vatandasAdTextFiled(evt);
            }
        });

        vatandasSifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vatandasSifreTextFiled(evt);
            }
        });

        btn.setText("Giris");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vatandasGirisButon(evt);
            }
        });

        btn1.setText("Kapat");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vatandasGirisKapatBotun(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 227, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vatandasName, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(vatandasSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(215, 215, 215))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(253, 253, 253)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn1))
                    .addComponent(jLabel1))
                .addGap(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(vatandasName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(vatandasSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btn)
                .addGap(18, 18, 18)
                .addComponent(btn1)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vatandasAdTextFiled(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vatandasAdTextFiled
        // TODO add your handling code here:
    }//GEN-LAST:event_vatandasAdTextFiled

    private void vatandasSifreTextFiled(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vatandasSifreTextFiled
        // TODO add your handling code here:
    }//GEN-LAST:event_vatandasSifreTextFiled

    private void vatandasGirisButon(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vatandasGirisButon
        // TODO add your handling code here:
        String name = vatandasName.getText();
        String sifre = vatandasSifre.getText();
        Citizen citizen = Citizen.getInstance();
        VatandasIslemleri vatandasIslemleri = new VatandasIslemleri();
        boolean bol = citizen.giris_Yap(name, sifre);
        
        if (vatandasName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lutfen Adinizi Giriniz", "Bos Alan", JOptionPane.ERROR_MESSAGE);
        }
        
        if (vatandasSifre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lutfen Sifrenizi Giriniz", "Bos Alan", JOptionPane.ERROR_MESSAGE);
        }
        
        if(bol){
            vatandasIslemleri.setLocationRelativeTo(null);
                vatandasIslemleri.setVisible(true);
                setVisible(false);
            }else{
                JOptionPane.showMessageDialog(null,"Yanlis Bilgi Girisi!!\nBilgilerinizden Emin Olup Bir Daha Deneyiniz");
            }
    }//GEN-LAST:event_vatandasGirisButon

    private void vatandasGirisKapatBotun(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vatandasGirisKapatBotun
        // TODO add your handling code here:
        setVisible(false);
        Home home = new Home();
        home.setLocationRelativeTo(null);
        home.setVisible(true);
    }//GEN-LAST:event_vatandasGirisKapatBotun

    private void metot1(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_metot1
        // TODO add your handling code here:
    }//GEN-LAST:event_metot1

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VatandasGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VatandasGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VatandasGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VatandasGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VatandasGiris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton btn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField vatandasName;
    private javax.swing.JTextField vatandasSifre;
    // End of variables declaration//GEN-END:variables
}
